export const AllProducts = [
  {
    title: "iPhone 15 Pro Max",
    price: 660579,
    oldPrice: 850000,
    discount: 22,
    imageUrl: "/images/IMG_9692.webp",
    category: "Iphones",
    slug: "product-1",
    description: "This is a detailed description of the product. It includes features, specifications, warranty details, and other relevant information to help customers make an informed decision.",
    specs: "Dual SIM', '5G Connectivity', 'IP68 Rating"
  },
  {
    title: "Samsung Galaxy S24 Ultra",
    price: 550000,
    oldPrice: 700000,
    discount: 21,
    imageUrl: "/images/IMG_9696.webp",
    category: "Samsung",
    slug: "product-2",
    description: "This is a detailed description of the product. It includes features, specifications, warranty details, and other relevant information to help customers make an informed decision.",
    specs: "Dual SIM', '5G Connectivity', 'IP68 Rating"
  },
  {
    title: "Itel 8 Pro",
    price: 480000,
    oldPrice: 600000,
    discount: 20,
    imageUrl: "/images/IMG_9707.webp",
    category: "Itel",
    slug: "product-3",
    description: "This is a detailed description of the product. It includes features, specifications, warranty details, and other relevant information to help customers make an informed decision.",
    specs: "Dual SIM', '5G Connectivity', 'IP68 Rating"
  },
  {
    title: "Xiaomi 14 Pro",
    price: 420000,
    oldPrice: 520000,
    discount: 19,
    imageUrl: "/images/IMG_9701.webp",
    category: "Redmi",
    slug: "product-4",
    description: "This is a detailed description of the product. It includes features, specifications, warranty details, and other relevant information to help customers make an informed decision.",
    specs: "Dual SIM', '5G Connectivity', 'IP68 Rating"
  },
  {
      title: "Xiaomi 14 Pro",
      price: 420000,
      oldPrice: 520000,
      discount: 19,
      imageUrl: "/images/IMG_9704.webp",
      category: "Redmi",
      slug: "product-5",
      description: "This is a detailed description of the product. It includes features, specifications, warranty details, and other relevant information to help customers make an informed decision.",
    specs: "Dual SIM', '5G Connectivity', 'IP68 Rating"
    },
    {
      title: "Xiaomi 14 Pro",
      price: 420000,
      oldPrice: 520000,
      discount: 19,
      imageUrl: "/images/IMG_9706.webp",
      category: "Redmi",
      slug: "product-6",
      description: "This is a detailed description of the product. It includes features, specifications, warranty details, and other relevant information to help customers make an informed decision.",
    specs: "Dual SIM', '5G Connectivity', 'IP68 Rating"
    },
    {
      title: "Xiaomi 14 Pro",
      price: 420000,
      oldPrice: 520000,
      discount: 19,
      imageUrl: "/images/IMG_9710.webp",
      category: "Accessories",
      slug: "product-7",
      description: "This is a detailed description of the product. It includes features, specifications, warranty details, and other relevant information to help customers make an informed decision.",
    specs: "Dual SIM', '5G Connectivity', 'IP68 Rating"
    },
    {
      title: "Xiaomi 14 Pro",
      price: 420000,
      oldPrice: 520000,
      discount: 19,
      imageUrl: "/images/IMG_9709.webp",
      category: "Accessories",
      slug: "product-8",
      description: "This is a detailed description of the product. It includes features, specifications, warranty details, and other relevant information to help customers make an informed decision.",
    specs: "Dual SIM', '5G Connectivity', 'IP68 Rating"
    },
    {
      title: "Xiaomi 14 Pro",
      price: 420000,
      oldPrice: 520000,
      discount: 19,
      imageUrl: "/images/IMG_9708.webp",
      category: "Redmi",
      slug: "product-9",
      description: "This is a detailed description of the product. It includes features, specifications, warranty details, and other relevant information to help customers make an informed decision.",
    specs: "Dual SIM', '5G Connectivity', 'IP68 Rating"
    },
    {
      title: "Xiaomi 14 Pro",
      price: 420000,
      oldPrice: 520000,
      discount: 19,
      imageUrl: "/images/IMG_9705.webp",
      category: "Redmi",
      slug: "product-10",
      description: "This is a detailed description of the product. It includes features, specifications, warranty details, and other relevant information to help customers make an informed decision.",
    specs: "Dual SIM', '5G Connectivity', 'IP68 Rating"
    },
    {
      title: "Xiaomi 14 Pro",
      price: 420000,
      oldPrice: 520000,
      discount: 19,
      imageUrl: "/images/IMG_9702.webp",
      category: "Accessories",
      slug: "product-11",
      description: "This is a detailed description of the product. It includes features, specifications, warranty details, and other relevant information to help customers make an informed decision.",
    specs: "Dual SIM', '5G Connectivity', 'IP68 Rating"
    },
    {
      title: "Xiaomi 14 Pro",
      price: 420000,
      oldPrice: 520000,
      discount: 19,
      imageUrl: "/images/IMG_9703.webp",
      category: "Accessories",
      slug: "product-12",
      description: "This is a detailed description of the product. It includes features, specifications, warranty details, and other relevant information to help customers make an informed decision.",
    specs: "Dual SIM', '5G Connectivity', 'IP68 Rating"
    },

    {
      title: "Xiaomi 14 Pro",
      price: 420000,
      oldPrice: 520000,
      discount: 19,
      imageUrl: "/images/IMG_9703.webp",
      category: "Iphones",
      slug: "product-13",
      description: "This is a detailed description of the product. It includes features, specifications, warranty details, and other relevant information to help customers make an informed decision.",
    specs: "Dual SIM', '5G Connectivity', 'IP68 Rating"
    },
    {
      title: "Xiaomi 14 Pro",
      price: 420000,
      oldPrice: 520000,
      discount: 19,
      imageUrl: "/images/IMG_9703.webp",
      category: "Iphones",
      slug: "product-14",
      description: "This is a detailed description of the product. It includes features, specifications, warranty details, and other relevant information to help customers make an informed decision.",
    specs: "Dual SIM', '5G Connectivity', 'IP68 Rating"
    },
    {
      title: "Xiaomi 14 Pro",
      price: 420000,
      oldPrice: 520000,
      discount: 19,
      imageUrl: "/images/IMG_9703.webp",
      category: "Techno",
      slug: "product-15",
      description: "This is a detailed description of the product. It includes features, specifications, warranty details, and other relevant information to help customers make an informed decision.",
    specs: "Dual SIM', '5G Connectivity', 'IP68 Rating"
    },
    {
      title: "Xiaomi 14 Pro",
      price: 420000,
      oldPrice: 520000,
      discount: 19,
      imageUrl: "/images/IMG_9703.webp",
      category: "Techno",
      slug: "product-16",
      description: "This is a detailed description of the product. It includes features, specifications, warranty details, and other relevant information to help customers make an informed decision.",
    specs: "Dual SIM', '5G Connectivity', 'IP68 Rating"
    },
    {
      title: "Xiaomi 14 Pro",
      price: 420000,
      oldPrice: 520000,
      discount: 19,
      imageUrl: "/images/IMG_9703.webp",
      category: "Infinix",
      slug: "product-17",
      description: "This is a detailed description of the product. It includes features, specifications, warranty details, and other relevant information to help customers make an informed decision.",
    specs: "Dual SIM', '5G Connectivity', 'IP68 Rating"
    },
    {
      title: "Xiaomi 14 Pro",
      price: 420000,
      oldPrice: 520000,
      discount: 19,
      imageUrl: "/images/IMG_9703.webp",
      category: "Infinix",
      slug: "product-18",
      description: "This is a detailed description of the product. It includes features, specifications, warranty details, and other relevant information to help customers make an informed decision.",
    specs: "Dual SIM', '5G Connectivity', 'IP68 Rating"
    },
    {
      title: "Xiaomi 14 Pro",
      price: 420000,
      oldPrice: 520000,
      discount: 19,
      imageUrl: "/images/IMG_9703.webp",
      category: "Itel",
      slug: "product-19",
      description: "This is a detailed description of the product. It includes features, specifications, warranty details, and other relevant information to help customers make an informed decision.",
    specs: "Dual SIM', '5G Connectivity', 'IP68 Rating"
    },
    {
      title: "Xiaomi 14 Pro",
      price: 420000,
      oldPrice: 520000,
      discount: 19,
      imageUrl: "/images/IMG_9703.webp",
      category: "Itel",
      slug: "product-20",
      description: "This is a detailed description of the product. It includes features, specifications, warranty details, and other relevant information to help customers make an informed decision.",
    specs: "Dual SIM', '5G Connectivity', 'IP68 Rating"
    },
    {
      title: "Xiaomi 14 Pro",
      price: 420000,
      oldPrice: 520000,
      discount: 19,
      imageUrl: "/images/IMG_9703.webp",
      category: "Itel",
      slug: "product-21",
      description: "This is a detailed description of the product. It includes features, specifications, warranty details, and other relevant information to help customers make an informed decision.",
    specs: "Dual SIM', '5G Connectivity', 'IP68 Rating"
    },
    {
      title: "Xiaomi 14 Pro",
      price: 420000,
      oldPrice: 520000,
      discount: 19,
      imageUrl: "/images/IMG_9703.webp",
      category: "Iphones",
      slug: "product-22",
      description: "This is a detailed description of the product. It includes features, specifications, warranty details, and other relevant information to help customers make an informed decision.",
    specs: "Dual SIM', '5G Connectivity', 'IP68 Rating"
    },
    {
      title: "Xiaomi 14 Pro",
      price: 420000,
      oldPrice: 520000,
      discount: 19,
      imageUrl: "/images/IMG_9703.webp",
      category: "Techno",
      slug: "product-23",
      description: "This is a detailed description of the product. It includes features, specifications, warranty details, and other relevant information to help customers make an informed decision.",
    specs: "Dual SIM', '5G Connectivity', 'IP68 Rating"
    },
    {
      title: "Xiaomi 14 Pro",
      price: 420000,
      oldPrice: 520000,
      discount: 19,
      imageUrl: "/images/IMG_9703.webp",
      category: "Infinix",
      slug: "product-24",
      description: "This is a detailed description of the product. It includes features, specifications, warranty details, and other relevant information to help customers make an informed decision.",
    specs: "Dual SIM', '5G Connectivity', 'IP68 Rating"
    },
    {
      title: "Xiaomi 14 Pro",
      price: 420000,
      oldPrice: 520000,
      discount: 19,
      imageUrl: "/images/IMG_9703.webp",
      category: "Techno",
      slug: "product-25",
      description: "This is a detailed description of the product. It includes features, specifications, warranty details, and other relevant information to help customers make an informed decision.",
    specs: "Dual SIM', '5G Connectivity', 'IP68 Rating"
    },
    {
      title: "Xiaomi 14 Pro",
      price: 420000,
      oldPrice: 520000,
      discount: 19,
      imageUrl: "/images/IMG_9703.webp",
      category: "Infinix",
      slug: "product-26",
      description: "This is a detailed description of the product. It includes features, specifications, warranty details, and other relevant information to help customers make an informed decision.",
    specs: "Dual SIM', '5G Connectivity', 'IP68 Rating"
    },
    {
      title: "Xiaomi 14 Pro",
      price: 420000,
      oldPrice: 520000,
      discount: 19,
      imageUrl: "/images/IMG_9703.webp",
      category: "Samsung",
      slug: "product-27",
      description: "This is a detailed description of the product. It includes features, specifications, warranty details, and other relevant information to help customers make an informed decision.",
    specs: "Dual SIM', '5G Connectivity', 'IP68 Rating"
    },
    {
      title: "Xiaomi 14 Pro",
      price: 420000,
      oldPrice: 520000,
      discount: 19,
      imageUrl: "/images/IMG_9703.webp",
      category: "Samsung",
      slug: "product-28",
      description: "This is a detailed description of the product. It includes features, specifications, warranty details, and other relevant information to help customers make an informed decision.",
    specs: "Dual SIM', '5G Connectivity', 'IP68 Rating"
    },
    {
      title: "Xiaomi 14 Pro",
      price: 420000,
      oldPrice: 520000,
      discount: 19,
      imageUrl: "/images/IMG_9703.webp",
      category: "Samsung",
      slug: "product-29",
      description: "This is a detailed description of the product. It includes features, specifications, warranty details, and other relevant information to help customers make an informed decision.",
    specs: "Dual SIM', '5G Connectivity', 'IP68 Rating"
    },
    {
      title: "Xiaomi 14 Pro",
      price: 420000,
      oldPrice: 520000,
      discount: 19,
      imageUrl: "/images/IMG_9703.webp",
      category: "Samsung",
      slug: "product-30",
      description: "This is a detailed description of the product. It includes features, specifications, warranty details, and other relevant information to help customers make an informed decision.",
    specs: "Dual SIM', '5G Connectivity', 'IP68 Rating"
    },
    {
      title: "Xiaomi 14 Pro",
      price: 420000,
      oldPrice: 520000,
      discount: 19,
      imageUrl: "/images/IMG_9703.webp",
      category: "Infinix",
      slug: "product-31",
      description: "This is a detailed description of the product. It includes features, specifications, warranty details, and other relevant information to help customers make an informed decision.",
    specs: "Dual SIM', '5G Connectivity', 'IP68 Rating"
    },
];
